
name: Update_COVID19_Argentina
env:
  REQ_PIP:  https://raw.githubusercontent.com/felixlapalma/covid19-argentina-viz/master/requirements.txt
on:
  schedule:
    - cron: '0 19 * * *'
jobs:
  chartUpdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ REQ_PIP }}
    - name: Update Covid Charts 
      run: jupyter nbconvert --to notebook --inplace --execute _notebooks/2020-03-18-argentina_covid19_viz.ipynb

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: felixlapalma
        author_email: felixlapalma@gmail.com
        message: "Update COVID19 JNB  ${{steps.date.outputs.date}}"
        add: "_notebooks/2020-03-18-argentina_covid19_viz.ipynb"
      env:
       GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
